Move dependencies from peerDependencies to dependencies
otovo/javascript pull request #5
Opened 2020-01-31 16:28 UTC by mortnod

In [Rainbow PR #21](https://github.com/otovo/rainbow/pull/21) I updated Rainbows dependencies. As part of that I upgraded ESLint from v5 to v6.

This change seemed to break the ESLint setup. The [v6 migration guide](https://eslint.org/docs/user-guide/migrating-to-6.0.0#package-loading-simplification) seemed to indicate that plugins must be installed locally now. Thus, the dependencies was moved out of `peerDependencies` and into `dependencies`. This fixed my problem.

I'm not quite sure about the implications of this change, though. Feedback (and alternative solutions) are greatly appreciated. 🙂

2020-02-11 08:12 UTC, kmkr approved these changes
Great! I don't think moving from peer to non-peer dependencies will cause problems.

2020-02-11 08:12 UTC, kmkr commented on package.json
> +  "peerDependencies": {},
Can be removed.

2020-02-11 08:12 UTC, kmkr commented on typescript/index.js
> +        'js': 'never',
I can't find it now but I remember reading the spec requires extensions for import. Any reason for disallowing extensions? What about ignoring the rule instead for now?

2020-02-24 10:31 UTC, rix1 requested changes
Nice work! Keeping deps up to date is important and I appreciate you taking the time to do this 🙌 

I tried this locally, and I had no issues with just upgrading the packages, but keeping them in peerDependencies 🤔  Maybe you encountered a different problem? Or is it because I don't have `eslint` installed globally? 

After seeing and agreeing with @kmkr's comment, I suggest that you split your commit into 2 (or three):
1. `Upgrade packages`
2. `Move from deps to peerDeps`
3. `typescript: update import/extensions`, and then add a rationale for why this was done 👍 

I guess you could do 1 and 2 in one go – you decide :)

2020-09-01 09:31 UTC, rix1 approved these changes

2020-09-01 09:32 UTC, rix1 commented
Upgraded all dependencies. Merging this now :v: Will publish to npm as soon as we're in master

2020-09-01 09:32 UTC, merged

2020-09-01 10:27 UTC, mortnod commented
![what-year-is-this](https://user-images.githubusercontent.com/3471625/91838848-6be51180-ec4e-11ea-9aed-530b7af28a2e.gif)

Thanks for dragging this across the finish line @rix1 ❤️